services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    # ðŸŒŸ NEW: This attaches a "Hard Drive" so data survives restarts
    volumes:
      - sentinel_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d sentinel_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sentinel-network

  sentinel-ai:
    build: ./sentinel-monitor
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sentinel-network

  core-engine:
    build: ./core-engine
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sentinel_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
      - sentinel-ai
    networks:
      - sentinel-network

  dashboard:
    build: ./sentinel-dashboard
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - core-engine
    networks:
      - sentinel-network

  web-service:
    build: ./web-service
    container_name: sentinel-web-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sentinel_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # âœ… Keep this as 'update' now!
    networks:
      - sentinel-network

#  db-seeder:
#    image: python:3.11-slim
#    volumes:
#      - ./sentinel-monitor:/app
#    working_dir: /app
#    depends_on:
#      db:
#        condition: service_healthy
#    command: >
#      sh -c "pip install psycopg2-binary && python app/seed.py"
#    networks:
#      - sentinel-network

# ðŸŒŸ NEW: Define the volume here
volumes:
  sentinel_data_v2:

networks:
  sentinel-network:
    driver: bridge